### ISSUE TITLE
how to LinearLayoutManager is LinearLayoutManager.HORIZONTAL

### ISSUE THREAD

**Issue by sunny0092** [skydoves/AndroidVeil#15]
**Is your feature request related to a problem?**
I changed LinearLayoutManager.HORIZONTAL but it didn't work

**Describe the solution you'd like:**
    holder.binding.recyclerViewContent.run {
                setVeilLayout(R.layout.item_home_feature_shimmer)
                setAdapter(featureHorizontalAdapter)
                setLayoutManager(LinearLayoutManager(context, LinearLayoutManager.HORIZONTAL, false))
                addVeiledItems(2)
}
           
thanks admin

**Comment by skydoves** [comment]
Actually, it is not supporting the `HORIZONTAL` now but I will consider adding the HORIZONTAL.
Thanks for your issue :)

**Comment by G00fY2** [comment]
This should be stated in the Readme!

**Comment by Jigar-zest** [comment]
Any ETA on this?

**Comment by avalanchas** [comment]
@skydoves do I see it correctly that we would have to set different layout params in the `VeilLayout:addMaskElements` to allow for horizontal alignment? Is this something you would accept a PR for?

**Comment by skydoves** [comment]
Hey guys, the new version 1.1.4 has been released, and now you can use `LinearLayoutManager.HORIZONTAL`.
