### ISSUE TITLE
Not working in MotionLayout

### ISSUE THREAD

**Issue by kaustav07** [skydoves/AndroidVeil#16]
**Please complete the following information:**
- Library Version - 1.1.1
- Affected Device(s) - Oneplus 6T , Android 10
 
**Describe the Bug:**

Added Simple VeilLayout inside Motionlayout, it just takes up the space, but that space is empty, no shimmer or anything but works fine in ConstraintLayout

**Expected Behavior:**

it should work

**Comment by skydoves** [comment]
Hey @kaustav07, 
Sorry for the late response. Currently, we don't have any plans to support MotionLayout, so I'll close this issue for now.
Thanks!
