### ISSUE TITLE
Not working on Textview

### ISSUE THREAD

**Issue by iamcadis** [skydoves/AndroidVeil#17]
- Library Version -> 1.1.1
- Affected Device(s) -> Xiaomi Note 8 Android 10
- Bug Desc
 
**Veil not working in TextView but work when TextTiew inside layout:

`<com.skydoves.androidveil.VeilLayout`
                    android:id="@+id/balance_layout"
                    android:layout_width="0dp"
                    android:layout_height="wrap_content"
                    android:layout_marginBottom="@dimen/large"
                    app:veilLayout_shimmerEnable="true"
                    app:layout_constraintEnd_toEndOf="@id/card_action"
                    app:layout_constraintStart_toStartOf="@id/card_action"
                    app:layout_constraintBottom_toTopOf="@id/card_action">

                    <TextView
                        android:id="@+id/balance"
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content"
                        android:text="@string/zero_balance"
                        android:textColor="?attr/colorOnSecondary"
                        android:textSize="@dimen/large_title"
                        android:textStyle="bold"/>

                </com.skydoves.androidveil.VeilLayout>`

**Comment by MuhaPW** [comment]
Translated using Yandex. Translate. 

I also encountered such a problem. Everything works, but VeilLayout can't calculate the size.
Your tree should look like this:

`<VeilLayout ...>
     <ViewGroup ...> 
         <TextView .../>
     <ViewGroup/>
 <ViewLayout/>`
 
Instead of ViewGroup, you need to add any other element that inherits from ViewGroup. For example, LinearLayout.

**Comment by skydoves** [comment]
Now you can reference a [demo](https://github.com/skydoves/AndroidVeil/tree/master/app) project to cover the `TextView`.
But I'm considering measuring the width size of the `TextView` internally in the future without using like `maxWidth` or `minWidth`.
