### ISSUE TITLE
Doesn't work with recycler view horizontal layout and having some shimmer visual bugs

### ISSUE THREAD

**Issue by IHateSyntaxErrors** [skydoves/AndroidVeil#18]
**Please complete the following information:**
- Library Version [e.g. v1.0.4]
- Affected Device(s) [e.g. Pixel 4 with Android 10.0]
 
**Describe the Bug:**

- Doesn't work with LinearLayoutManager.HORIZONTAL
- For some reason when the veiled is under effect, it cuts the view in half and I am not sure why, I tried experimenting around but no luck
 
![image](https://user-images.githubusercontent.com/5959474/119266396-54422480-bbf3-11eb-9d08-0097ef9cd458.png)

Once everything is loaded:
![image](https://user-images.githubusercontent.com/5959474/119266441-86538680-bbf3-11eb-9e6c-5ddaf809ff7d.png)

**Comment by skydoves** [comment]
Same as #15.
