### ISSUE TITLE
version 1.1.1 does not contain your recent change for SetlayoutManager 

### ISSUE THREAD

**Issue by balwinderSingh1989** [skydoves/AndroidVeil#20]
your below commit is not released with latest version 1.1.2
https://github.com/skydoves/AndroidVeil/commit/6a268761b076b97aafeede1221ac65a541a9db74#diff-5d0bbee114d99970fe8ee64b121efd7368651652b224802264dbc7fc1bbfb898

**Comment by skydoves** [comment]
`1.1.2` has been released!
