### ISSUE TITLE
The recyclerView needs an addOnScrollListener() method

### ISSUE THREAD

**Issue by jrcacd** [skydoves/AndroidVeil#3]

**Comment by skydoves** [comment]
@jrcacd Hello! Thank you for your issue!
It seems getRecyclerView() method will resolve all of your issues.
It will be added to the next version. Thank you!

**Comment by skydoves** [comment]
@jrcacd
v1.0.2 is released!
You can access recyclerViews using below methods

```java
veilRecyclerView.getRecyclerView()
veilRecyclerView.getVeiledRecyclerView()
```

**Comment by jrcacd** [comment]
Thanks
