### ISSUE TITLE
Implementing veil using the view reference.

### ISSUE THREAD

**Issue by ShreyashSaitwal** [skydoves/AndroidVeil#9]
Hi there,
Would it be possible to add a way to implement veil on a layout by referencing it's view? For example: 
``` 
View mLayout = layout.getView();
veilLayout.layout = mLayout;
```
Currently, the only way to set a layout programmatically is by using layout resources, and due to some reasons I can't use it. It'd be great if you could introduce me with some way to use it with view reference. :)

**Comment by skydoves** [comment]
@ShreyashSaitwal 
Hi, a new version `1.0.8` is released now!
You can set the like this:

```kotlin
val inflater = LayoutInflater.from(this)
detail_veilLayout_body.setLayout(inflater.inflate(R.layout.item_profile, detail_veilLayout_body ,false))
```

If you want to apply the margin and padding values of the veillayout, you should set the veillayout as a parent.
But If you want to set the layout which is a ViewGroup, you don't need it.
Thank you for your issue :)

**Comment by ShreyashSaitwal** [comment]
Thanks a bunch!

**Comment by ShreyashSaitwal** [comment]
Hi @skydoves,
Can you please show me an example in Java?
Thanks.
